// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VfH_JcfVqldgCdTMQJUaPSGtBaGlv9U',
    appId: '1:856472644621:web:d59985e1a4fa84087c3944',
    messagingSenderId: '856472644621',
    projectId: 'sesion07-jean01',
    authDomain: 'sesion07-jean01.firebaseapp.com',
    storageBucket: 'sesion07-jean01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUssdIsDBS7msG0Td0RbV7wh3NU6voaE',
    appId: '1:856472644621:android:7d1d78ef3e7ea1047c3944',
    messagingSenderId: '856472644621',
    projectId: 'sesion07-jean01',
    storageBucket: 'sesion07-jean01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDZXzuKuubAqx06msPXiLduRO2BOh9A0',
    appId: '1:856472644621:ios:ef21827be4feb0537c3944',
    messagingSenderId: '856472644621',
    projectId: 'sesion07-jean01',
    storageBucket: 'sesion07-jean01.appspot.com',
    iosClientId: '856472644621-bplhp3u124l33cfodnkisbpddnecnbc7.apps.googleusercontent.com',
    iosBundleId: 'com.eje0802frb.eje0802',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDZXzuKuubAqx06msPXiLduRO2BOh9A0',
    appId: '1:856472644621:ios:ef21827be4feb0537c3944',
    messagingSenderId: '856472644621',
    projectId: 'sesion07-jean01',
    storageBucket: 'sesion07-jean01.appspot.com',
    iosClientId: '856472644621-bplhp3u124l33cfodnkisbpddnecnbc7.apps.googleusercontent.com',
    iosBundleId: 'com.eje0802frb.eje0802',
  );
}
